project:
  type: website

execute: 
  freeze: auto

website:
  title: "Steven Golovkine"
  site-url: https://stevengolovkine.netlify.app
  description: Personal website
  repo-url: https://github.com/StevenGolovkine/website
  navbar:
    title: "<span class='vl'>Steven<span class='hl'></span>Golovkine</span>"
    right:
      - href: contents/about.qmd
        text: About
      - href: contents/research.qmd
        text: Research
      - href: contents/talks.qmd
        text: Talks
      - href: contents/code.qmd
        text: Code
      - href: contents/posts.qmd
        text: Posts
      - href: contents/contact.qmd
        text: Contact
      

format:
  html:
    theme:
      light: themes/light_theme.scss
      dark: themes/dark_theme.scss
    css: themes/theme.css
    smooth-scroll: true
    link-external-newwindow: true
