project:
  type: website

execute: 
  freeze: auto

website:
  title: "Steven Golovkine"
  site-url: https://stevengolovkine.netlify.app
  description: Personal website
  repo-url: https://github.com/StevenGolovkine/website
  navbar:
    title: "> SG"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: themes/light_theme.scss
      dark: themes/dark_themes.scss
    smooth-scroll: true
    link-external-newwindow: true
